import { test, expect } from '@playwright/test';

test('theme persists, follows the system and works with forms on mobile', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.emulateMedia({ colorScheme: 'light' });
  await page.goto('/');
  const theme = page.getByLabel('Tema de la aplicación', { exact: true });
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
  await theme.selectOption('dark');
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await page.reload();
  await expect(theme).toHaveValue('dark');
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await page.getByRole('button', { name: 'Nuevo movimiento', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByLabel('Importe (€)')).toBeVisible();
  await page.getByRole('button', { name: 'Cancelar', exact: true }).click();
  await theme.selectOption('system');
  await page.emulateMedia({ colorScheme: 'dark' });
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await page.emulateMedia({ colorScheme: 'light' });
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
  await page.getByRole('button', { name: 'Explorar demo', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Tu dinero, con perspectiva' })).toBeVisible();
  await page.getByText('Ver importes por mes', { exact: true }).click();
  await expect(page.locator('.history-details tbody tr')).toHaveCount(6);
  await page.getByRole('button', { name: 'Mes anterior', exact: true }).click();
  await page.getByRole('button', { name: 'Mes actual', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Mes actual', exact: true })).toHaveCount(0);
  await page.setViewportSize({ width: 390, height: 844 });
  await theme.selectOption('dark');
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/mobile-dark.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: 'test-results/desktop-dark.png', fullPage: true });
  await theme.selectOption('light');
  await page.screenshot({ path: 'test-results/desktop-light.png', fullPage: true });
  expect(errors).toEqual([]);
});
