import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test.beforeEach(async ({page}) => { await page.clock.setFixedTime(new Date('2026-09-28T12:00:00')); await page.goto('/'); });

test('recurring payments, pause, exports and backup roundtrip', async ({page}) => {
  await page.getByRole('button',{name:'Suscripciones',exact:true}).click();
  await page.getByRole('button',{name:'Añadir suscripción',exact:true}).click();
  await page.getByLabel('Servicio',{exact:true}).fill('Gimnasio');
  await page.getByLabel('Importe (€)').fill('30');
  await page.getByLabel('Próximo pago').fill('2026-09-15');
  await page.getByRole('button',{name:'Guardar suscripción',exact:true}).click();
  await page.getByRole('button',{name:'Pausar',exact:true}).click();
  await expect(page.getByRole('button',{name:'Registrar pago',exact:true})).toBeDisabled();
  await page.getByRole('button',{name:'Reanudar',exact:true}).click();
  await page.getByRole('button',{name:'Registrar pago',exact:true}).click();
  await expect(page.getByText(/Próximo pago: 2026-10-15/)).toBeVisible();
  await expect(page.getByRole('button',{name:'Registrar pago',exact:true})).toBeDisabled();
  await page.getByRole('button',{name:'Movimientos',exact:true}).click();
  await expect(page.locator('tbody tr')).toHaveCount(1);
  let download = page.waitForEvent('download');
  await page.getByRole('button',{name:'Exportar CSV',exact:true}).click();
  const csv = await readFile((await (await download).path())!, 'utf8');
  expect(csv).toContain('Gimnasio'); expect(csv).toContain('30,00');
  download = page.waitForEvent('download');
  await page.getByRole('button',{name:'Exportar PDF',exact:true}).click();
  const pdf = await readFile((await (await download).path())!);
  expect(pdf.subarray(0,5).toString()).toBe('%PDF-');
  await page.getByRole('button',{name:'Ajustes',exact:true}).click();
  download = page.waitForEvent('download');
  await page.getByRole('button',{name:'Exportar copia JSON',exact:true}).click();
  const backup = await readFile((await (await download).path())!);
  expect(JSON.parse(backup.toString()).recurring[0].nextDate).toBe('2026-10-15');
  page.on('dialog', d => d.accept());
  await page.locator('input[type=file]').setInputFiles({name:'copia.json',mimeType:'application/json',buffer:backup});
  await expect(page.getByRole('status')).toContainText('restaurada');
  await page.getByRole('button',{name:'Suscripciones',exact:true}).click();
  await expect(page.getByText(/Próximo pago: 2026-10-15/)).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
